# Generated by Django 4.0 on 2022-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_player_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('joiner', models.CharField(max_length=100)),
                ('betamount', models.CharField(max_length=10)),
            ],
        ),
    ]
