# Generated by Django 4.0 on 2022-08-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ownerChoice',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='betamount',
            field=models.IntegerField(),
        ),
    ]
