# Generated by Django 4.0 on 2022-08-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_game_ownerchoice_alter_game_betamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='ownerChoice',
            new_name='ownersChoice',
        ),
    ]
