# Generated by Django 4.0 on 2022-08-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_game_ownerschoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ownerChoice',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
