# Generated by Django 4.0 on 2022-08-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_player_coins_player_losses_player_wins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='betamount',
            new_name='betAmount',
        ),
    ]
