# Generated by Django 4.0 on 2022-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_betamount_game_betamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
