# Generated by Django 4.0 on 2022-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_joiner_game_joinername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='joinerChoice',
            field=models.CharField(default='', max_length=100),
        ),
    ]
