# Generated by Django 4.0 on 2022-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
