# Generated by Django 4.0 on 2022-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_player_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='negatives',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='positives',
            field=models.IntegerField(default=0),
        ),
    ]
